apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: min-ia
  namespace: pia
  labels:
    team: pia
    created-by: pia
spec:
  groups:
    - name: min-ia-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="min-ia"} == 0
          for: 2m
          annotations:
            consequence: "Forebygge fravær er utilgjengelig"
            action: |-
              Sjekk helsa til applikasjonen ved å kjøre
              `kubectl describe pod <podname> -n pia` og 
              `kubectl logs <podname> -n pia`"
          labels:
            namespace: pia
            severity: critical

        - alert: ErrorLogRegistrert
          expr: sum(increase(logd_messages_total{log_app="min-ia", log_level="Error"}[10m])) > 0
          annotations:
            description: "Forebygge fravær frontend har logget en (eller flere) feil."
            action: |-
              Sjekk logs.adeo.no for logger, 
              eller Grafana-dashboardet vårt: https://grafana.nais.io/dashboards/f/cvOhCMUnz/team-ia
          labels:
            namespace: pia
            severity: warning