apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "https://arbeidsgiver.nav.no/forebygge-fravar/sykefravarsstatistikk/$2"
    prometheus.io/scrape: "false"
  labels:
    app: min-ia
    team: pia
  name: prod-redirect-sykefravarsstatistikk-to-forebygge-fravar
  namespace: pia
spec:
  ingressClassName: nais-ingress-external
  rules:
    - host: arbeidsgiver.nav.no
      http:
        paths:
          - backend:
              service:
                name: sykefravarsstatistikk
                port:
                  number: 80
            path: /sykefravarsstatistikk(/|$)(.*)
            pathType: ImplementationSpecific
